# Promise 2

The function `asyncNumberChecker` takes a number as a parameter and returns a Promise. This promise resolves to a message if the number is less than 10 and an error if the number is 10 or greater. 

**Challenge** handle the promise and log the message returned when the promise is rejected. 

Hint: You need to add `.then()` and `.catch()`

**Challenge** Call the `asyncNumberChecker` again, below the first example, with a number less than 10. Print the returned message.
